FROM centos:8

RUN yum update \
    && yum install -y iputils \
    && yum install -y ncurses \
    && yum install -y openssl \
    && yum install -y perl \
    && yum install -y nc && \
    yum clean all && \
    rm -rf /var/cache/yum

# RUN update-crypto-policies --set FUTURE

CMD ["/bin/tail", "-f", "/etc/hosts"]