FROM centos:7

RUN yum update -y \
    && yum install -y iputils \
    && yum install -y ncurses \
    && yum install -y openssl \
    && yum install -y perl \
    && yum install -y nc \
    && yum clean -y all && \
    rm -rf /var/cache/yum

CMD ["/bin/tail", "-f", "/etc/hosts"]