version: '2'
services:
  puppet:
    build: base-puppet/.
    image: didricg/puppetbase
  rsqe:
    build: base-rsqe/.
    image: didricg/rsqe
    command: tail -f /dev/null
    depends_on:
      - puppet 
    volumes:
      - ./ecosystem-puppet-docker/puppet/modules/applications:/test-puppet/example_env/modules
      - ./ecosystem-puppet-docker/puppet/manifests:/test-puppet/manifests
  nginx:
    build: base-nginx/.
    image: didricg/nginx
    #command: nginx
    ports:
      - "80:80"
    depends_on:
      - puppet 
    volumes:
      - .:/code
      - ./www:/usr/local/nginx/html
  jenkins-master:
    build: base-jenkins/.
    image: didricg/jenkins-master
    ports:
      - "8080:8080"
    depends_on:
      - puppet 
